/* global XLSX */
const COLUMNS = [
  'mcmv_ogu_01_dt_referencia','mcmv_ogu_02_dt_geracao','mcmv_ogu_03_cod_ibge','mcmv_ogu_04_nome_municipio','mcmv_ogu_05_cod_operacao_snh','mcmv_ogu_06_cod_operacao_af','mcmv_ogu_07_txt_nome_af','mcmv_ogu_08_txt_nome_construtora_entidade','mcmv_ogu_09_txt_cnpj_construtora_entidade','mcmv_ogu_10_txt_nome_empreendimento','mcmv_ogu_11_txt_programa','mcmv_ogu_12_txt_faixa','mcmv_ogu_13_txt_modalidade','mcmv_ogu_14_txt_situacao_empreendimento','mcmv_ogu_15_txt_detalhamento_situacao_obra','mcmv_ogu_16_dt_contratacao','mcmv_ogu_17_perc_obra','mcmv_ogu_18_val_contratado_original','mcmv_ogu_19_val_aporte_adicional','mcmv_ogu_20_val_contratado_total','mcmv_ogu_21_val_desembolsado','mcmv_ogu_22_qtd_uh','mcmv_ogu_23_qtd_entregues','mcmv_ogu_24_qtd_distratadas','mcmv_ogu_25_qtd_vigentes','mcmv_ogu_26_dt_termino','mcmv_ogu_27_txt_sigla_uf','mcmv_ogu_28_txt_uf','mcmv_ogu_29_txt_regiao','mcmv_ogu_30_qtd_vigentes_janeiro_ano_dt_referencia','mcmv_ogu_31_qtd_entregues_ano_dt_referencia','mcmv_ogu_32_txt_situacao_janeiro_ano_dt_referencia','mcmv_ogu_33_vlr_desembolsado_no_ano_dt_referencia','mcmv_ogu_34_txt_detalhamento_situacao_jan_ano_dt_referencia','mcmv_ogu_35_txt_situacao_obra_agrupada','mcmv_ogu_36_bln_vigente','mcmv_ogu_37_bln_novo_mcmv','mcmv_ogu_38_qtd_entregues_2023','mcmv_ogu_39_qtd_uh_vigentes_jan_23','mcmv_ogu_40_txt_situacao_jan_23','mcmv_ogu_41_txt_detalhamento_situacao_jan_23','mcmv_ogu_42_situacao_obra_agrupada_jan_23','mcmv_ogu_44_bln_vigente_jan_23','mcmv_ogu_45_txt_logradouro','mcmv_ogu_46_txt_numero_imovel','mcmv_ogu_47_txt_complemento_logradouro','mcmv_ogu_48_txt_bairro_imovel','mcmv_ogu_49_txt_cep_imovel','mcmv_ogu_50_txt_latitude_imovel','mcmv_ogu_51_txt_longitude_imovel'
];
const COL = Object.fromEntries(COLUMNS.map((x, i) => [x, i]));
const K = (n) => COLUMNS.find(x => x.includes(`_${String(n).padStart(2, '0')}_`));
const TEXT = [4,7,8,10,11,12,13,14,15,27,28,29,32,34,35,36,37,40,41,42,44,45,47,48];
const NUM = [3,5,6,17,18,19,20,21,22,23,24,25,30,31,33,38,39,46,49,50,51];
const IMP = 'IMPEDITIVO', ACE = 'ACEITÁVEL';
const ERR_VALUES = ['#N/D','#NOME?','#VALOR!','#REF!','#DIV/0!'];
const allowed = {
  12:['Faixa 1'],13:['Entidades','FAR','FAR - Compra Assistida','FNHIS','Oferta Pública','Rural'],
  14:['CONCLUÍDO E ENTREGUE','DESIMOBILIZADO','DISTRATADO/CANCELADO','EM ANDAMENTO','FASE PROJETO','OBRA NÃO INICIADA','PARALISADO'],
  15:['A RETOMAR - AO/MCI/ASSINATURA','A RETOMAR - APORTE SUPLEMENTAR','A RETOMAR - SOLUÇÃO LOCAL','INDICATIVO DESIMOBILIZAÇÃO','NÃO SE APLICA','OCUPAÇÃO IRREGULAR','OCUPADO, EM LEGALIZAÇÃO','REDUÇÃO DE META','RESCISÃO DA OPERAÇÃO'],
  27:['AC','AL','AM','AP','BA','CE','DF','ES','GO','MA','MG','MS','MT','PA','PB','PE','PI','PR','RJ','RN','RO','RR','RS','SC','SE','SP','TO'],
  29:['Centro-Oeste','Nordeste','Norte','Sudeste','Sul'],35:['Concluído','Distratado','Em Andamento','Fase Projeto','Paralisado - a Distratar','Paralisado - a Retomar','Paralisado - Ocupado'],36:['Sim','Não'],37:['Sim','Não'],44:['Sim','Não'],
  32:['Concluído e Entregue','Concluído e Entregue com Pendência de Legalização','Concluído e Entregue sem Pendências','Desimobilizado','Distratado','Distratado/Cancelado','Em Andamento','Fase de Projeto','Obra Não Iniciada','Paralisado','Selecionado'],
  34:['A Retomar','A RETOMAR - AO/MCI/ASSINATURA','A RETOMAR - APORTE SUPLEMENTAR','A retomar - Em Análise','A RETOMAR - EM CONSTRUÇÃO DA PROPOSTA','A RETOMAR - SOLUÇÃO LOCAL','Aguarda documentos de última parcela','Indicativo de Desimobilização','INDICATIVO DESIMOBILIZAÇÃO','NÃO SE APLICA','Ocupação Irregular','OCUPADO, EM LEGALIZAÇÃO','PNHR','REDUÇÃO DE META','Rescisão da Operação','RESCISÃO OPERAÇÃO'],
  40:['Concluído e entregue com pendência de legalização','Concluído e entregue com pendência de pagamento do Trabalho Social','CONCLUÍDO E ENTREGUE SEM PENDÊNCIAS','DISTRATADO/CANCELADO','EM ANDAMENTO','FASE DE PROJETO','Não iniciado','PARALISADO'],
  41:['A ENTREGAR','A RETORMAR','A RETORMAR - APORTE SUPLEMENTAR','A RETORMAR - EM ANÁLISE','A RETORMAR - SOLUÇÃO LOCAL','APORTE LOCAL EXTRAPOLA O TETO','INDICATIVO DESIMOBILIZAÇÃO','Indicativo para Desimobilização','OCUPAÇÃO IRREGULAR','OCUPADO, EM LEGALIZAÇÃO','Ocupados/Invadidos','Outros','PNHR','REDUÇÃO DE META','RESCISÃO OPERAÇÃO','Retomada autorizada','Retomada em tramitação','SUPLEMENTAÇÃO DE OBRA NÃO INCIDENTE'],
  42:['Distratado','Em Andamento','Fase Projeto','Paralisado - a Distratar','Paralisado - a Retomar','Paralisado - Ocupado']
};
const STATES = {
  'Acre':['AC','Norte'],'Alagoas':['AL','Nordeste'],'Amapá':['AP','Norte'],'Amazonas':['AM','Norte'],'Bahia':['BA','Nordeste'],'Ceará':['CE','Nordeste'],'Distrito Federal':['DF','Centro-Oeste'],'Espírito Santo':['ES','Sudeste'],'Goiás':['GO','Centro-Oeste'],'Maranhão':['MA','Nordeste'],'Mato Grosso':['MT','Centro-Oeste'],'Mato Grosso do Sul':['MS','Centro-Oeste'],'Minas Gerais':['MG','Sudeste'],'Pará':['PA','Norte'],'Paraíba':['PB','Nordeste'],'Paraná':['PR','Sul'],'Pernambuco':['PE','Nordeste'],'Piauí':['PI','Nordeste'],'Rio de Janeiro':['RJ','Sudeste'],'Rio Grande do Norte':['RN','Nordeste'],'Rio Grande do Sul':['RS','Sul'],'Rondônia':['RO','Norte'],'Roraima':['RR','Norte'],'Santa Catarina':['SC','Sul'],'São Paulo':['SP','Sudeste'],'Sergipe':['SE','Nordeste'],'Tocantins':['TO','Norte']
};
let selectedFile, outputWorkbook, outputName, referenceBase;
const $ = id => document.getElementById(id);
const cell = (row, n) => row[COL[K(n)]];
const empty = v => v === undefined || v === null || String(v).trim() === '';
const same = (a,b) => Math.abs((Number(a)||0)-(Number(b)||0)) < 0.00001;
const asText = v => empty(v) ? '' : String(v).trim();
const normalized = v => asText(v).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toUpperCase();
function num(v) { if (typeof v === 'number') return v; if (empty(v)) return null; const n = Number(String(v).replace(/\./g,'').replace(',', '.')); return Number.isFinite(n) ? n : NaN; }
function date(v) { if (v instanceof Date && !isNaN(v)) return v; if (typeof v === 'number') return XLSX.SSF.parse_date_code(v) ? new Date(Date.UTC(1899,11,30 + v)) : null; if (empty(v)) return null; const m=String(v).trim().match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/); if (!m) return null; const d=new Date(Number(m[3]),Number(m[2])-1,Number(m[1])); return isNaN(d)||d.getDate()!=+m[1] ? null : d; }
function fmtDate(d) { return `${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`; }
function logChange(changes, line, column, from, to, why) { changes.push([line, `${column}: “${from}” → “${to}”`, why]); }
function set(row,n,value,changes,line,why) { const i=COL[K(n)], before=row[i]; if (String(before??'')!==String(value??'')) { row[i]=value; logChange(changes,line,K(n),before??'',value??'',why); } }
function makeLog(logs, line, rule, level=ACE) { logs.push({rule,line,level}); }
function inAllowed(v, list) { return list.some(item => normalized(item) === normalized(v)); }
function styleSheet(ws, rows) {
  const range=XLSX.utils.decode_range(ws['!ref']);
  for(let R=range.s.r;R<=range.e.r;R++) for(let C=range.s.c;C<=range.e.c;C++) { const a=XLSX.utils.encode_cell({r:R,c:C}); if(!ws[a]) continue; const level=R>0 ? rows[R-1]?.[2] : ''; ws[a].s={font:{bold:R===0},fill:{fgColor:{rgb:R===0?'D9E1F2':level===IMP?'F4CCCC':level===ACE?'FFF2CC':'FFFFFF'}},border:{top:{style:'thin',color:{rgb:'000000'}},bottom:{style:'thin',color:{rgb:'000000'}},left:{style:'thin',color:{rgb:'000000'}},right:{style:'thin',color:{rgb:'000000'}}}}; }
  ws['!cols']=[{wch:62},{wch:18},{wch:15}]; ws['!autofilter']={ref:ws['!ref']};
}
function checkRow(row, line, logs, changes) {
  // Correções de tipo e formato permitidas pelas regras gerais.
  [41,46,47].forEach(n => { const v=cell(row,n); if (!empty(v) && Number(num(v)) === 0) set(row,n,'',changes,line,'Valor zero substituído por vazio, conforme regra específica.'); });
  TEXT.forEach(n => { const v=cell(row,n); if (typeof v==='number') set(row,n,'',changes,line,'Valor numérico em coluna textual substituído por vazio.'); });
  NUM.forEach(n => { const v=cell(row,n); if (typeof v==='string' && v.trim() && n!==49) set(row,n,0,changes,line,'Valor textual em coluna numérica substituído por zero.'); });
  [1,2,16,26].forEach(n => { const v=cell(row,n), d=date(v); if(!empty(v) && d) set(row,n,fmtDate(d),changes,line,'Data convertida para o formato DD/MM/AAAA.'); });
  const replacements={15:{'RESCISÃO OPERAÇÃO':'RESCISÃO DA OPERAÇÃO'},34:{'Indicativo de Desimobilização':'INDICATIVO DESIMOBILIZAÇÃO','Rescisão da Operação':'RESCISÃO OPERAÇÃO'},41:{'Indicativo para Desimobilização':'INDICATIVO DESIMOBILIZAÇÃO'}};
  Object.entries(replacements).forEach(([n,map])=>{const v=asText(cell(row,+n)); if(map[v]) set(row,+n,map[v],changes,line,'Padronização prevista na regra específica.');});
  const cnpj=asText(cell(row,9)); if(cnpj) { const ds=cnpj.replace(/\D/g,'').padStart(14,'0'); if(ds.length===14) set(row,9,`${ds.slice(0,2)}.${ds.slice(2,5)}.${ds.slice(5,8)}/${ds.slice(8,12)}-${ds.slice(12)}`,changes,line,'CNPJ formatado como XX.XXX.XXX/XXXX-XX.'); }
  const dates=[1,2,16,26].map(n=>date(cell(row,n))); const [ref,ger,contract,end]=dates;
  if(ref){ const formattedRef=fmtDate(ref); if(!referenceBase) referenceBase=formattedRef; else if(formattedRef!==referenceBase) makeLog(logs,line,'Data de Referência deve ser igual em todas as linhas da planilha.',IMP); }
  const req=(n,label,level=ACE)=>{if(empty(cell(row,n)))makeLog(logs,line,`${label}: não pode estar vazio.`,level)};
  const checkDate=(n,label)=>{if(!date(cell(row,n)))makeLog(logs,line,`${label}: deve ser data no formato DD/MM/AAAA.`,ACE)};
  [1,2,16,26].forEach(n=>{if(!empty(cell(row,n)))checkDate(n,K(n));});
  if(ref&&ger&&ger<=ref)makeLog(logs,line,'Data de Geração deve ser maior que Data de Referência.',IMP);
  if(contract&&contract<=new Date(2009,0,1))makeLog(logs,line,'Data da Contratação deve ser posterior a 01/01/2009.',IMP);
  if(contract&&ref&&contract>=ref)makeLog(logs,line,'Data da Contratação deve ser inferior à Data de Referência.',IMP);
  if(end&&ref&&end>=ref)makeLog(logs,line,'Data de Término deve ser anterior à Data de Referência.',IMP);
  if(end&&contract&&end<=contract)makeLog(logs,line,'Data de Término deve ser posterior à Data da Contratação.',IMP);
  const ibge=asText(cell(row,3)); if(!/^\d{6}$/.test(ibge))makeLog(logs,line,'Código IBGE deve ser numérico e possuir 6 dígitos.',IMP);
  if(asText(cell(row,4)) && !/^[A-ZÁÀÃÂÉÊÍÓÔÕÚÇ]/.test(asText(cell(row,4))))makeLog(logs,line,'Nome do Município deve iniciar com maiúscula.',ACE);
  if(!(num(cell(row,5))>0))makeLog(logs,line,'Código da Operação SNH deve ser maior que zero.',IMP);
  const af=asText(cell(row,6)), afName=normalized(cell(row,7)); if(afName==='BB'&&!/^\d{6,8}$/.test(af))makeLog(logs,line,'Código da Operação AF para BB deve possuir de 6 a 8 dígitos.',ACE); if(afName==='CAIXA'&&!/^\d{7,8}$/.test(af))makeLog(logs,line,'Código da Operação AF para Caixa deve possuir de 7 a 8 dígitos.',ACE); if(!['BB','CAIXA'].includes(afName)&&!empty(af))makeLog(logs,line,'Código da Operação AF deve estar vazio para os demais agentes financeiros.',ACE);
  [8,10].forEach(n=>{req(n,K(n),ACE); if(ERR_VALUES.includes(asText(cell(row,n))))makeLog(logs,line,`${K(n)} não pode conter erro de fórmula.`,IMP)}); req(9,K(9),ACE); if(cnpj&&ERR_VALUES.includes(cnpj))makeLog(logs,line,'CNPJ não pode conter erro de fórmula.',IMP);
  Object.entries(allowed).forEach(([n,list])=>{const v=cell(row,+n); if(!empty(v)&&!inAllowed(v,list))makeLog(logs,line,`${K(+n)} possui valor fora da lista permitida.`,IMP);});
  [32,35,36,37,44].forEach(n=>req(n,K(n),ACE));
  const det=normalized(cell(row,15)), situation=normalized(cell(row,14)); const onlyPar=['A RETOMAR - AO/MCI/ASSINATURA','A RETOMAR - APORTE SUPLEMENTAR','A RETOMAR - SOLUÇÃO LOCAL','INDICATIVO DESIMOBILIZAÇÃO','OCUPAÇÃO IRREGULAR','REDUÇÃO DE META','RESCISÃO DA OPERAÇÃO'].map(normalized);
  if(onlyPar.includes(det)&&situation!=='PARALISADO')makeLog(logs,line,'Detalhamento de situação permitido somente para empreendimento PARALISADO.',IMP); if(det===normalized('OCUPADO, EM LEGALIZAÇÃO')&&situation!==normalized('EM ANDAMENTO'))makeLog(logs,line,'OCUPADO, EM LEGALIZAÇÃO exige situação EM ANDAMENTO.',IMP); if(['',normalized('NÃO SE APLICA')].includes(det)&&situation==='PARALISADO')makeLog(logs,line,'Em branco ou NÃO SE APLICA não é permitido para empreendimento PARALISADO.',IMP);
  const numeric = (n,label,{required=false,min,max,requiredLevel=ACE,rangeLevel=IMP}={})=>{const v=cell(row,n), x=num(v); if(required&&empty(v))makeLog(logs,line,`${label}: não pode estar vazio.`,requiredLevel); if(!empty(v)&&!Number.isFinite(x))makeLog(logs,line,`${label}: deve ser numérico.`,ACE); if(Number.isFinite(x)&&min!==undefined&&x<min)makeLog(logs,line,`${label}: deve ser maior ou igual a ${min}.`,rangeLevel); if(Number.isFinite(x)&&max!==undefined&&x>max)makeLog(logs,line,`${label}: deve ser menor ou igual a ${max}.`,rangeLevel); return x;};
  const pct=numeric(17,'Percentual de obra',{required:true,min:0,max:100,rangeLevel:ACE}), original=numeric(18,'Valor Contratado Original',{required:true,min:0,requiredLevel:IMP}), aporte=numeric(19,'Valor do Aporte Adicional',{min:0}), total=numeric(20,'Valor Contratado Total',{required:true,min:0,requiredLevel:ACE}), paid=numeric(21,'Valor Desembolsado',{min:0});
  if(original!==null&&original<=0)makeLog(logs,line,'Valor Contratado Original deve ser maior que zero.',IMP); if(total!==null&&total<=0)makeLog(logs,line,'Valor Contratado Total deve ser maior que zero.',IMP); if(original!==null&&total!==null&&!same(original+(aporte||0),total))makeLog(logs,line,'Valor Contratado Total deve ser a soma do valor original e do aporte adicional.',IMP); if(paid!==null&&total!==null&&paid>total)makeLog(logs,line,'Valor Desembolsado não pode ser maior que o Valor Contratado Total.',IMP);
  const uh=numeric(22,'Quantidade de UH Contratadas',{required:true,min:0,requiredLevel:IMP}), delivered=numeric(23,'Quantidade de UH Entregues',{min:0}), cancelled=numeric(24,'Quantidade de UH Distratadas',{min:0}), active=numeric(25,'Quantidade de UH Vigentes',{min:0}); if(uh!==null&&uh<=0)makeLog(logs,line,'Quantidade de UH Contratadas deve ser maior que zero.',IMP); [delivered,cancelled,active].forEach((v,i)=>{if(v!==null&&uh!==null&&v>uh)makeLog(logs,line,[ 'Quantidade de UH Entregues','Quantidade de UH Distratadas','Quantidade de UH Vigentes'][i]+' não pode ser maior que a quantidade contratada.',IMP);}); if(uh!==null&&![delivered,cancelled,active].some(v=>v===null)&&!same(delivered+cancelled+active,uh))makeLog(logs,line,'Entregues + distratadas + vigentes deve ser igual à quantidade de UH contratadas.',IMP); if(active!==null&&uh!==null&&!same(active,uh-(delivered||0)-(cancelled||0)))makeLog(logs,line,'Quantidade de UH Vigentes deve ser contratadas menos entregues e distratadas.',IMP); if(normalized(cell(row,35))===normalized('Distratado')&&(!(cancelled>0)||!same(cancelled,(uh||0)-(delivered||0))))makeLog(logs,line,'Empreendimento Distratado exige quantidade distratada compatível.',IMP);
  const state=asText(cell(row,28)); if(!STATES[state])makeLog(logs,line,'UF possui valor fora da lista permitida.',IMP); else {if(asText(cell(row,27))!==STATES[state][0])makeLog(logs,line,'Sigla da UF não corresponde ao estado.',IMP);if(asText(cell(row,29))!==STATES[state][1])makeLog(logs,line,'Região não corresponde ao estado.',IMP);}
  [30,31,39].forEach(n=>{const x=numeric(n,K(n),{min:0});if(x!==null&&uh!==null&&x>uh)makeLog(logs,line,`${K(n)} não pode ser maior que UH contratadas.`,IMP);}); const x38=numeric(38,K(38),{min:0,rangeLevel:ACE});if(x38!==null&&uh!==null&&x38>uh)makeLog(logs,line,`${K(38)} não pode ser maior que UH contratadas.`,IMP);if(x38!==null&&delivered!==null&&x38>delivered)makeLog(logs,line,`${K(38)} não pode ser maior que UH Entregues.`,IMP); const r31=num(cell(row,31));if(r31!==null&&delivered!==null&&r31>delivered)makeLog(logs,line,'UH Entregues no Ano de Referência não pode ser maior que UH Entregues.',IMP); const yearPaid=numeric(33,'Valor Desembolsado no Ano de Referência',{min:0});if(yearPaid!==null&&paid!==null&&yearPaid>paid)makeLog(logs,line,'Valor Desembolsado no Ano de Referência não pode ser maior que o desembolsado.',IMP); if(yearPaid!==null&&total!==null&&yearPaid>total)makeLog(logs,line,'Valor Desembolsado no Ano de Referência não pode ser maior que o contratado total.',IMP);
  if(contract&&contract.getFullYear()>=2024){[38,39].forEach(n=>{if(!empty(cell(row,n))&&num(cell(row,n))!==0)makeLog(logs,line,`${K(n)} deve ser zero ou vazio para contratação a partir de 2024.`,IMP);});if(!['','Não iniciado'].includes(asText(cell(row,40))))makeLog(logs,line,'Situação em Janeiro de 2023 deve ser Não iniciado ou vazia para contratação a partir de 2024.',IMP);if(!['','Outros'].includes(asText(cell(row,41))))makeLog(logs,line,'Detalhamento em Janeiro de 2023 deve ser Outros ou vazio para contratação a partir de 2024.',IMP);if(!empty(cell(row,42)))makeLog(logs,line,'Situação Agrupada em Janeiro de 2023 deve ser vazia para contratação a partir de 2024.',IMP);}
  const cep=asText(cell(row,49)); if(cep&&/^\d{1,8}$/.test(cep)&&cep.length<8)set(row,49,cep.padStart(8,'0'),changes,line,'CEP preenchido com zeros à esquerda para totalizar 8 dígitos.'); const homeNo=num(cell(row,46));if(!empty(cell(row,46))&&!Number.isFinite(homeNo))makeLog(logs,line,'Número do Imóvel deve ser numérico.',ACE);if(!empty(cell(row,46))&&empty(cell(row,45)))makeLog(logs,line,'Número do Imóvel preenchido exige Logradouro.',ACE);if(!empty(cell(row,47))&&(empty(cell(row,45))||empty(cell(row,46))))makeLog(logs,line,'Complemento preenchido exige Logradouro e Número do Imóvel.',ACE);if(!empty(cell(row,48))&&empty(cell(row,45)))makeLog(logs,line,'Bairro preenchido exige Logradouro.',ACE);if(!/^\d{8}$/.test(asText(cell(row,49))))makeLog(logs,line,'CEP deve ser numérico e possuir 8 dígitos.',ACE);
}
function createLogSheets(wb, logs, changes) {
  ['LOG RESUMO','LOG DETALHAMENTO','ALTERAÇÕES'].forEach(n=>{if(wb.SheetNames.includes(n)){delete wb.Sheets[n];wb.SheetNames.splice(wb.SheetNames.indexOf(n),1);}});
  const grouped=new Map();logs.forEach(x=>{const k=`${x.rule}|${x.level}`;grouped.set(k,(grouped.get(k)||0)+1)}); const summary=[['Regra não atendida','Quantidade de linhas','Classificação'],...Array.from(grouped,([k,count])=>{const [rule,level]=k.split('|');return [rule,count,level]})]; const detail=[['Regra não atendida','Linha','Classificação'],...logs.map(x=>[x.rule,x.line,x.level])]; const changeRows=[['Número da linha alterada','Alteração realizada','Justificativa'],...changes];
  [['LOG RESUMO',summary],['LOG DETALHAMENTO',detail],['ALTERAÇÕES',changeRows]].forEach(([name,rows])=>{const ws=XLSX.utils.aoa_to_sheet(rows);styleSheet(ws,rows);XLSX.utils.book_append_sheet(wb,ws,name);});
}
function processFile() {
  const status=$('status'); if(!selectedFile)return; try { status.className='status'; status.textContent='Lendo e conferindo a planilha…'; const reader=new FileReader(); reader.onload=e=>{try { const wb=XLSX.read(e.target.result,{type:'array',cellDates:false,raw:true,cellStyles:true}); const ws=wb.Sheets[wb.SheetNames[0]]; const data=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:true}); const headers=data[0]||[]; const missing=COLUMNS.filter(h=>!headers.includes(h)); if(missing.length)throw new Error(`A primeira aba não contém todos os cabeçalhos oficiais. Faltam: ${missing.join(', ')}.`); const ordered=data.slice(1).filter(r=>r.some(v=>!empty(v))).map(r=>COLUMNS.map(h=>r[headers.indexOf(h)]??'')); const logs=[],changes=[]; ordered.forEach((r,i)=>checkRow(r,i+2,logs,changes)); const clean=XLSX.utils.aoa_to_sheet([COLUMNS,...ordered]); clean['!cols']=COLUMNS.map(()=>({wch:18})); wb.Sheets[wb.SheetNames[0]]=clean; createLogSheets(wb,logs,changes); outputWorkbook=wb; outputName=selectedFile.name.replace(/\.(xlsx|xls)$/i,'')+'_conferido.xlsx'; const imp=logs.filter(x=>x.level===IMP).length, ace=logs.length-imp; $('linhas').textContent=ordered.length;$('impeditivos').textContent=imp;$('aceitaveis').textContent=ace;$('alteracoes').textContent=changes.length;$('resultado').classList.remove('hidden');$('baixar').classList.remove('hidden');status.className='status ok';status.textContent='Conferência concluída. Baixe o arquivo para acessar os relatórios.';}catch(err){status.className='status error';status.textContent=err.message||'Não foi possível processar o arquivo.';}}; reader.readAsArrayBuffer(selectedFile);}catch(err){status.className='status error';status.textContent=err.message;}
}
$('arquivo').addEventListener('change',e=>{selectedFile=e.target.files[0];referenceBase=undefined;$('arquivo-nome').textContent=selectedFile?selectedFile.name:'Nenhum arquivo selecionado.';$('processar').disabled=!selectedFile;$('resultado').classList.add('hidden');});
$('processar').addEventListener('click',processFile); $('baixar').addEventListener('click',()=>XLSX.writeFile(outputWorkbook,outputName,{cellStyles:true}));
