let selectedFile, reportRows=[], worker, usingLocalProcessor=false;
const $=id=>document.getElementById(id);
const localProcessor=window.onmessage;
const nativePostMessage=window.postMessage.bind(window);
const REGRAS_APLICADAS=[
['1','Estrutura','O CSV deve conter os 23 cabeçalhos oficiais do FGTS.','IMPEDITIVO'],['2','01 e 02','Datas válidas; referência uniforme; geração não anterior à referência.','IMPEDITIVO'],['3','03','Código de Agrupamento SNH preenchido e único.','IMPEDITIVO'],['4','04','Código IBGE numérico com 6 dígitos.','IMPEDITIVO'],['5','06 a 08','Programa federal, modalidade e programa FGTS dentro das listas permitidas.','IMPEDITIVO'],['6','09, 20 e 21','Data de contratação em AAAAMM, compatível com ano/mês e não posterior à referência.','IMPEDITIVO'],['7','10 a 13','Valores financeiros numéricos e não negativos.','IMPEDITIVO'],['8','10 e 11','Valor da compra maior ou igual ao valor do financiamento.','IMPEDITIVO'],['9','14','Quantidade de contratos inteira e maior que zero.','IMPEDITIVO'],['10','15','Faixa dentro da lista permitida.','IMPEDITIVO'],['11','16','Tipo do imóvel: Novo ou Usado; vazio é apontamento de atenção.','ATENÇÃO'],['12','17 a 19 e 22','UF, estado, região e sigla da região compatíveis.','IMPEDITIVO'],['13','23','Fonte de recurso dentro da lista permitida.','IMPEDITIVO'],['14','06, 15 e 23','Faixa 3 FS exige fonte Fundo Social; demais faixas MCMV exigem programa federal MCMV ou CVA.','IMPEDITIVO']
];

REGRAS_APLICADAS.push(['15','04, 05 e 17','Código IBGE, município e sigla da UF devem corresponder à base territorial oficial DTB 2024 do IBGE.','IMPEDITIVO']);
function csvEscape(value){const text=String(value??'');return /[";\n\r]/.test(text)?`"${text.replaceAll('"','""')}"`:text;}
function csvText(rows){return `\uFEFF${rows.map(row=>row.map(csvEscape).join(';')).join('\r\n')}`;}
function crc32(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return(crc^0xffffffff)>>>0;}
function zipStore(entries){const encoder=new TextEncoder(),local=[],central=[];let offset=0;for(const [name,text] of entries){const filename=encoder.encode(name),data=encoder.encode(text),crc=crc32(data),header=new Uint8Array(30+filename.length),view=new DataView(header.buffer);view.setUint32(0,0x04034b50,true);view.setUint16(4,20,true);view.setUint32(14,crc,true);view.setUint32(18,data.length,true);view.setUint32(22,data.length,true);view.setUint16(26,filename.length,true);header.set(filename,30);local.push(header,data);const directory=new Uint8Array(46+filename.length),dirView=new DataView(directory.buffer);dirView.setUint32(0,0x02014b50,true);dirView.setUint16(4,20,true);dirView.setUint16(6,20,true);dirView.setUint32(16,crc,true);dirView.setUint32(20,data.length,true);dirView.setUint32(24,data.length,true);dirView.setUint16(28,filename.length,true);dirView.setUint32(42,offset,true);directory.set(filename,46);central.push(directory);offset+=header.length+data.length;}const centralSize=central.reduce((sum,item)=>sum+item.length,0),end=new Uint8Array(22),endView=new DataView(end.buffer);endView.setUint32(0,0x06054b50,true);endView.setUint16(8,entries.length,true);endView.setUint16(10,entries.length,true);endView.setUint32(12,centralSize,true);endView.setUint32(16,offset,true);return new Blob([...local,...central,end],{type:'application/zip'});}
function renderSummary(summary){const rows=Object.entries(summary).sort((a,b)=>b[1]-a[1]);$('resumo').innerHTML=rows.length?`<table><thead><tr><th>Regra</th><th>Ocorrências</th><th>Classificação</th></tr></thead><tbody>${rows.map(([key,count])=>{const [rule,level]=key.split('|');return `<tr><td>${rule}</td><td>${count}</td><td>${level}</td></tr>`;}).join('')}</tbody></table>`:'<p class="muted">Nenhuma inconsistência foi identificada.</p>';}
function receiveMessage(message){if(message.type==='progress'){$('barra').style.width=`${message.percent}%`;$('status').textContent=`Carregando e analisando: ${message.percent}% · ${message.records.toLocaleString('pt-BR')} registros.`;}
if(message.type==='complete'){reportRows=message.rows;$('registros').textContent=message.records.toLocaleString('pt-BR');$('impeditivos').textContent=message.impeditivos.toLocaleString('pt-BR');$('aceitaveis').textContent=message.aceitaveis.toLocaleString('pt-BR');renderSummary(message.summary);$('resultado').classList.remove('hidden');$('baixar').classList.remove('hidden');$('processar').disabled=false;$('barra').style.width='100%';$('status').className='status ok';$('status').textContent='Conferência concluída. O relatório contém somente as ocorrências identificadas.';restorePostMessage();}
if(message.type==='error'){$('processar').disabled=false;$('status').className='status error';$('status').textContent=message.message;restorePostMessage();}}
function restorePostMessage(){if(usingLocalProcessor){window.postMessage=nativePostMessage;usingLocalProcessor=false;}}
function startProcessing(file){try{if(!worker){worker=new Worker('worker.js');worker.onmessage=event=>receiveMessage(event.data);worker.onerror=()=>startLocalProcessing(file);}worker.postMessage({type:'process',file});}catch(error){startLocalProcessing(file);}}
function startLocalProcessing(file){if(usingLocalProcessor)return;usingLocalProcessor=true;window.postMessage=message=>receiveMessage(message);$('status').textContent='Carregando e analisando localmente… 0%';Promise.resolve(localProcessor({data:{type:'process',file}})).catch(error=>receiveMessage({type:'error',message:error.message||'Não foi possível processar o CSV.'}));}

$('arquivo').addEventListener('change',event=>{selectedFile=event.target.files[0];$('arquivo-nome').textContent=selectedFile?`${selectedFile.name} — ${(selectedFile.size/1024/1024).toFixed(1)} MB`:'Nenhum arquivo selecionado.';$('processar').disabled=!selectedFile;$('resultado').classList.add('hidden');$('status').textContent='';$('barra').style.width='0';});
$('processar').addEventListener('click',()=>{if(!selectedFile)return;reportRows=[];$('processar').disabled=true;$('barra').style.width='0';$('status').className='status';$('status').textContent='Carregando o arquivo e iniciando a conferência… 0%';startProcessing(selectedFile);});
function summaryRows(){const totals=reportRows.reduce((acc,row)=>{const key=`${row[1]}|${row[2]}`;acc[key]=(acc[key]||0)+1;return acc;},{});return Object.entries(totals).map(([key,count])=>{const [rule,level]=key.split('|');return [rule,count,level];});}
function buildSheet(rows,classificationColumn){const ws=XLSX.utils.aoa_to_sheet(rows);const cols=Math.max(...rows.map(row=>row.length));for(let r=0;r<rows.length;r++)for(let c=0;c<cols;c++){const address=XLSX.utils.encode_cell({r,c});if(!ws[address])continue;const level=r>0&&classificationColumn!==undefined?rows[r][classificationColumn]:'';ws[address].s={font:{bold:r===0},fill:{fgColor:{rgb:r===0?'D9D9D9':level==='IMPEDITIVO'?'F4CCCC':level==='ATENÇÃO'?'FFF2CC':'FFFFFF'}},border:{top:{style:'thin',color:{rgb:'000000'}},bottom:{style:'thin',color:{rgb:'000000'}},left:{style:'thin',color:{rgb:'000000'}},right:{style:'thin',color:{rgb:'000000'}}}};}ws['!cols']=Array.from({length:cols},(_,index)=>({wch:index===1?62:index===4?45:22}));ws['!autofilter']={ref:XLSX.utils.encode_range({s:{r:0,c:0},e:{r:rows.length-1,c:cols-1}})};return ws;}
function downloadZipFallback(detailHeader,summaryHeader,summary,rulesHeader){const blob=zipStore([['log_resumo.csv',csvText([summaryHeader,...summary])],['log_detalhamento.csv',csvText([detailHeader,...reportRows])],['regras_aplicadas.csv',csvText([rulesHeader,...REGRAS_APLICADAS])]]);const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`relatorio_fgts_${new Date().toISOString().slice(0,10)}.zip`;link.click();URL.revokeObjectURL(link.href);}
$('baixar').addEventListener('click',()=>{const detailHeader=['Código de Agrupamento SNH','Regra não atendida','Classificação','Valor encontrado','Justificativa','Município','UF','Data de contratação'];const summaryHeader=['Regra não atendida','Quantidade de ocorrências','Classificação'];const rulesHeader=['Número da regra','Colunas','Regra','Classificação'];const summary=summaryRows();if(!window.XLSX){$('status').className='status error';$('status').textContent='Não foi possível carregar o componente de geração do Excel. Verifique a conexão com a internet e tente novamente.';return;}if(reportRows.length>1048575){downloadZipFallback(detailHeader,summaryHeader,summary,rulesHeader);$('status').className='status';$('status').textContent='O detalhamento excede o limite de linhas do Excel; foi gerado um pacote ZIP de CSVs.';return;}const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,buildSheet([summaryHeader,...summary],2),'LOG RESUMO');XLSX.utils.book_append_sheet(book,buildSheet([detailHeader,...reportRows],2),'LOG DETALHAMENTO');XLSX.utils.book_append_sheet(book,buildSheet([rulesHeader,...REGRAS_APLICADAS],3),'REGRAS APLICADAS');XLSX.writeFile(book,`relatorio_fgts_${new Date().toISOString().slice(0,10)}.xlsx`,{cellStyles:true});});
